plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.10'
    id "io.spring.dependency-management" version '1.1.6'
    id "com.autonomousapps.dependency-analysis" version "3.6.1"
    id 'jacoco'
}

group = 'com.sprint.mission'
version = '3.0-M12'

repositories {
    mavenCentral()
}

dependencies {
    implementation platform('org.springdoc:springdoc-openapi:2.8.5')
    implementation platform('software.amazon.awssdk:bom:2.42.31')

    compileOnly("org.projectlombok:lombok:1.18.42")
    annotationProcessor("org.projectlombok:lombok:1.18.42")
    compileOnly('org.mapstruct:mapstruct:1.6.3')
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    annotationProcessor('org.mapstruct:mapstruct-processor:1.6.3')
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    implementation('org.springframework.boot:spring-boot-starter-web')
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation('org.springframework.boot:spring-boot-starter-validation')
    implementation('org.springdoc:springdoc-openapi-starter-webmvc-ui')
    implementation('org.springframework.boot:spring-boot-starter-data-jpa')
    implementation('org.springframework.boot:spring-boot-starter-aop')
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation('software.amazon.awssdk:s3')
    implementation('org.flywaydb:flyway-core')
    implementation('org.flywaydb:flyway-database-postgresql')
    implementation("com.nimbusds:nimbus-jose-jwt:10.9")
    implementation('org.springframework.retry:spring-retry')
    implementation('org.springframework.boot:spring-boot-starter-websocket')
    implementation('org.springframework.security:spring-security-messaging')

    implementation 'io.github.openfeign.querydsl:querydsl-jpa:7.1'
    annotationProcessor 'io.github.openfeign.querydsl:querydsl-apt:7.1:jpa'
    annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
    annotationProcessor 'jakarta.persistence:jakarta.persistence-api'

    developmentOnly('org.springframework.boot:spring-boot-devtools')
    runtimeOnly('org.postgresql:postgresql:42.7.7')
    runtimeOnly 'me.paulschwarz:spring-dotenv:4.0.0'

    testCompileOnly("org.projectlombok:lombok:1.18.42")
    testCompileOnly('org.mapstruct:mapstruct:1.6.3')
    testAnnotationProcessor("org.projectlombok:lombok:1.18.42")
    testAnnotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    testAnnotationProcessor('org.mapstruct:mapstruct-processor:1.6.3')

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation('org.springframework.boot:spring-boot-starter-test')
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation('org.testcontainers:postgresql')
    testImplementation('org.testcontainers:junit-jupiter')
}

tasks.register('copyFrontApiJson', Copy) {
    from "${project.rootDir}/discodeit-front/api.json"
    into "${project.projectDir}/src/main/resources/static"
}

tasks.named('processResources') {
    dependsOn copyFrontApiJson
}

tasks.named('test') {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
        csv.required = true
    }
    classDirectories.setFrom(files(classDirectories.files.collect {
        fileTree(dir: it).exclude { element ->
            def path = element.relativePath.pathString.replace('\\', '/')
            if (path.contains("/mapper/") || path.contains("/dto/")) return true
            if (path.contains("Discodeit.class")) return true
            if (path.contains("Interceptor") || path.contains("Filter")) return true
            if (path.matches(".*Q[A-Z].*")) return true

            if (path.contains("/common/")) {
                return !path.contains("/common/support/")
            }

            if (path.contains("/global/")) {
                return !(path.contains("/global/security/") || path.contains("/global/infra/") || path.contains("/global/validation/"))
            }

            if (path.contains("/domain/entity/")) {
                if (path.endsWith("UserCredential.class") || path.endsWith("RefreshToken.class") ||
                        path.endsWith("User.class") || path.endsWith("Message.class")) {
                    return false
                }
                return true
            }

            if (path.contains("/domain/")) {
                return true
            }

            return false
        }
    }))
}

import java.awt.*

jacocoTestReport {
    doLast {
        boolean isBuildTaskRun = gradle.startParameter.taskNames.contains('build')

        if (isBuildTaskRun) {
            def reportFile = file("${layout.buildDirectory.get()}/reports/jacoco/test/html/index.html")
            if (reportFile.exists() && Desktop.isDesktopSupported()) {
                Desktop.getDesktop().browse(reportFile.toURI())
            }
        }
    }
}
