services:
  app:
    build: .
    image: discodeit-backend:2.0-M9
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_PRESIGNED_URL_EXPIRATION: ${AWS_S3_PRESIGNED_URL_EXPIRATION}
      STORAGE_TYPE: ${STORAGE_TYPE}
      LOCAL_STORAGE_ROOT_PATH: ${LOCAL_STORAGE_ROOT_PATH}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

  web-server:
    build:
      context: discodeit-front
    image: discodeit-frontend:2.0.7
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - local-uploads:/usr/share/nginx/html/uploads
    environment:
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_REGION: ${AWS_S3_REGION}

volumes:
  local-uploads:
