discodeit:
  repository:
    type: jcf # jcf | file
    file-directory: .discodeit
  uuid:
    type: dev # dev / prod

springdoc:
  swagger-ui:
    url: /api/api-docs_1.1.json

spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: PostgreSQL
    defer-datasource-initialization: false