springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

spring:
  sql:
    init:
      mode: never

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: PostgreSQL
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 500
    open-in-view: false

logging:
  level:
    root: warn
    com.sprint.mission.discodeit: info
    org.hibernate.orm.jdbc.bind: warn
    org.hibernate.SQL: warn

  file:
    name: .logs/discodeit.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      clean-history-on-start: true
      max-history: 30
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
